## **Bag of Words**

In [1]:
import  numpy as np
import pandas as pd

In [6]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                   "dswithbappy watch dswithbappy",
                  "people write comment",
                  "dswithbappy write comment"
                   ],"output":[1,1,0,0]})
df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [9]:
bow = cv.fit_transform(df['text'])

In [10]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}

In [11]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [13]:
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [15]:
X = bow.toarray()
Y = df['output']
X
Y

0    1
1    1
2    0
3    0
Name: output, dtype: int64

### **N-grams**

In [16]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                   "dswithbappy watch dswithbappy",
                  "people write comment",
                  "dswithbappy write comment"
                   ],"output":[1,1,0,0]})
df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [25]:
#BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,3))

In [26]:
bow = cv.fit_transform(df['text'])

In [27]:
print(cv.vocabulary_)

{'people': 6, 'watch': 11, 'dswithbappy': 1, 'people watch': 7, 'watch dswithbappy': 12, 'people watch dswithbappy': 8, 'dswithbappy watch': 2, 'dswithbappy watch dswithbappy': 3, 'write': 13, 'comment': 0, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'dswithbappy write': 4, 'dswithbappy write comment': 5}

## **TF-IDF** - Term frequency - Inverse document frequency

In [28]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                   "dswithbappy watch dswithbappy",
                  "people write comment",
                  "dswithbappy write comment"
                   ],"output":[1,1,0,0]})
df

                            text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

In [32]:
tfid.fit_transform(df['text']).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])